"""
Step 3 – DPU-Accelerated Inference on Kria KV260 using Vitis-AI
This script performs hardware-accelerated inference using the Xilinx DPU
on the Kria KV260 platform.
Workflow:
1. Load the custom-generated DPU bitstream (.bit)
2. Load the compiled Vitis-AI model (.xmodel)
3. Quantize and preprocess CIFAR-10 input images
4. Execute inference on the DPU
5. Measure performance metrics:
    • Accuracy
    • Total inference time
    • Average latency per image
    • Throughput (FPS)
Toolchain:
- Vitis-AI
- PYNQ-DPU runtime
- Custom DPU bitstream (DPUCZDX8G)
- INT8 quantized model
This step demonstrates the performance gains achieved through
hardware acceleration compared to CPU-only execution.
"""
import os
import argparse
import numpy as np
import pickle
from time import time
from pynq_dpu import DpuOverlay

parser = argparse.ArgumentParser(description="DPU-accelerated CIFAR-10 inference on Kria KV260")
parser.add_argument("--bit",     type=str, default="bitstream/dpu.bit",    help="Path to DPU bitstream (.bit)")
parser.add_argument("--xmodel",  type=str, default="model/model.xmodel",   help="Path to compiled Vitis-AI model (.xmodel)")
parser.add_argument("--dataset", type=str, default="cifar-10-batches-py",  help="Path to CIFAR-10 dataset directory")
args = parser.parse_args()

BIT_PATH    = args.bit
XMODEL_PATH = args.xmodel
CIFAR_DIR   = args.dataset
def load_cifar10_test(cifar_dir: str):
    test_batch = os.path.join(cifar_dir, "test_batch")
    if not os.path.exists(test_batch):
        raise FileNotFoundError(f"Missing CIFAR test_batch at: {test_batch}")
    with open(test_batch, "rb") as f:
        batch = pickle.load(f, encoding="bytes")
    x_flat = batch[b"data"]                         
    y = np.array(batch[b"labels"], dtype=np.int64)  
    x = x_flat.reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1) 
    x = x.astype(np.float32) / 255.0                       
    return x, y
def tensor_fix_point(tensor):
    """Return fix_point if available, else None."""
    try:
        return tensor.get_attr("fix_point")
    except Exception:
        return None
def tensor_dtype(tensor):
    """Return dtype if available, else np.float32."""
    try:
        return tensor.dtype
    except Exception:
        return np.float32
# Fixed-point quantization helper
# The DPU operates on INT8/UINT8 data.
# fix_point defines the scaling factor (2^fix_point)
# used during quantization-aware compilation.
def quantize_input(img_f32_01, fix_point, dtype):
    """
    img_f32_01: float32 image in [0,1]
    fix_point: int, scale exponent where scale = 2**fix_point
    dtype: expected input dtype (np.int8 or np.uint8)
    """
    scale = 2 ** fix_point
    q = np.round(img_f32_01 * scale)

    if dtype == np.int8:
        q = np.clip(q, -128, 127).astype(np.int8)
    elif dtype == np.uint8:
        q = np.clip(q, 0, 255).astype(np.uint8)
    else:
        q = img_f32_01.astype(np.float32)
    return q
if not os.path.exists(BIT_PATH):
    raise FileNotFoundError(f"Bitstream not found: {BIT_PATH}")
if not os.path.exists(XMODEL_PATH):
    raise FileNotFoundError(f"XMODEL not found: {XMODEL_PATH}")
if not os.path.exists(CIFAR_DIR):
    raise FileNotFoundError(f"CIFAR directory not found: {CIFAR_DIR}")
print("Loading DPU overlay...")
# Load FPGA overlay containing the custom DPU
# This programs the FPGA fabric with the DPUCZDX8G
# accelerator generated in Step 3 (Vitis flow).
overlay = DpuOverlay(BIT_PATH)
print("Loading xmodel...")
# Load the compiled INT8 model into the DPU
# The .xmodel is generated by the Vitis-AI compiler
# and is specific to the DPU architecture and bitstream.
overlay.load_model(XMODEL_PATH)
dpu = overlay.runner
# Query DPU input/output tensor metadata
# This information is required to correctly:
#  - Quantize inputs
#  - Dequantize outputs
#  - Match tensor shapes and data types
input_tensors = dpu.get_input_tensors()
output_tensors = dpu.get_output_tensors()
in_shape  = tuple(input_tensors[0].dims)   
out_shape = tuple(output_tensors[0].dims)
in_fix  = tensor_fix_point(input_tensors[0])
out_fix = tensor_fix_point(output_tensors[0])
in_dt = tensor_dtype(input_tensors[0])
print("\nDPU Tensor Info")
print("Input shape: ", in_shape)
print("Output shape:", out_shape)
print("Input dtype: ", in_dt)
print("Input fix_point:", in_fix)
print("Output fix_point:", out_fix)
x_test, y_test = load_cifar10_test(CIFAR_DIR)
N = x_test.shape[0]
if (in_fix is not None) and (in_dt in (np.int8, np.uint8)):
    input_buf = np.empty(in_shape, dtype=in_dt, order="C")
else:
    input_buf = np.empty(in_shape, dtype=np.float32, order="C")
output_buf = np.empty(out_shape, dtype=np.float32, order="C")
output_size = int(output_tensors[0].get_data_size() / in_shape[0])
warm_n = min(10, N)
# Warmup phase:
# Run a few inferences before timing to:
#  - Initialize DPU pipelines
#  - Avoid first-run overhead
#  - Ensure stable performance measurements
print(f"\nWarmup on {warm_n} images...")
for i in range(warm_n):
    img = x_test[i]
    if (in_fix is not None) and (in_dt in (np.int8, np.uint8)):
        input_buf[0] = quantize_input(img, in_fix, in_dt)
        inp = [input_buf]
    else:
        input_buf[0] = img
        inp = [input_buf]
    job_id = dpu.execute_async(inp, [output_buf])
    dpu.wait(job_id)
# Performance measurement:
# - Accuracy is measured over the full CIFAR-10 test set
# - Throughput is calculated as images per second (FPS)
# - Latency is reported as average ms per image
print(f"\nRunning DPU inference on {N} images...")
y_pred = np.empty_like(y_test)
t0 = time()
for i in range(N):
    img = x_test[i]
    if (in_fix is not None) and (in_dt in (np.int8, np.uint8)):
        input_buf[0] = quantize_input(img, in_fix, in_dt)
        inp = [input_buf]
    else:
        input_buf[0] = img
        inp = [input_buf]
    job_id = dpu.execute_async(inp, [output_buf])
    dpu.wait(job_id)
    out = output_buf.reshape(-1)[:output_size]
    if out_fix is not None:
        out = out / (2 ** out_fix)
    y_pred[i] = int(np.argmax(out))
t1 = time()
acc = float(np.mean(y_pred == y_test) * 100.0)
total = t1 - t0
fps = (N / total) if total > 0 else float("inf")
avg_ms = (total / N) * 1000.0
# Final performance summary
# Demonstrates speedup and efficiency gains achieved
# through FPGA-based DPU acceleration.
print("\nResults")
print(f"Accuracy:        {acc:.2f}%")
print(f"Total time:      {total:.3f} sec")
print(f"Throughput:      {fps:.2f} FPS")
print(f"Avg ms/image:    {avg_ms:.3f} ms")
del dpu
del overlay
print("\nReleased DPU resources.")
# End of Step 3: Hardware-accelerated inference successfully completed.